language: python

python:
  - "3.7"
  
jdk:
  - oraclejdk8

install:
  - pip install -r requirements.txt
  
script:
  - wget https://github.com/ontodev/robot/releases/download/v1.7.0/robot.jar
  - wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
  - chmod u+x robot
  - export PATH=$PATH:`pwd`
  - cd src
  - make all
