site_name: ASCT+B Validation Reports
site_url: https://hubmapconsortium.github.io/ccf-validation-tools/
theme:
  name: material
  custom_dir: overrides
  features:
    - search.suggest
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Dashboard: dashboard.md
  - ASCT+B tables:
    - Anatomical Systems:
      - General report: Anatomical_Systems/README.md
      - ASCT+B as Graph: Anatomical_Systems/graph.md
      - Report changes: Anatomical_Systems/comments.md
    - Blood:
      - General report: Blood/README.md
      - ASCT+B as Graph: Blood/graph.md
      - Report changes: Blood/comments.md
    - Blood Vascularure:
      - General report: Blood_vasculature/README.md
      - ASCT+B as Graph: Blood_vasculature/graph.md
      - Report changes: Blood_vasculature/comments.md
    - Bone Marrow:
      - General report: Bone-Marrow/README.md
      - ASCT+B as Graph: Bone-Marrow/graph.md
      - Report changes: Bone-Marrow/comments.md
    - Brain:
      - General report: Brain/README.md
      - ASCT+B as Graph: Brain/graph.md
      - Report changes: Brain/comments.md
    - Eye:
      - General report: Eye/README.md
      - ASCT+B as Graph: Eye/graph.md
      - Report changes: Eye/comments.md
      - Change suggestions: Eye/relationship_validation.md
    - Fallopian Tube:
      - General report: Fallopian_tube/README.md
      - ASCT+B as Graph: Fallopian_tube/graph.md
      - Report changes: Fallopian_tube/comments.md
    - Heart:
      - General report: Heart/README.md
      - ASCT+B as Graph: Heart/graph.md
      - Report changes: Heart/comments.md
    - Kidney:
      - General report: Kidney/README.md
      - ASCT+B as Graph: Kidney/graph.md
      - Report changes: Kidney/comments.md
    - Knee:
      - General report: Knee/README.md
      - ASCT+B as Graph: Knee/graph.md
      - Report changes: Knee/comments.md
    - Large Intestine:
      - General report: Large_intestine/README.md
      - ASCT+B as Graph: Large_intestine/graph.md
      - Report changes: Large_intestine/comments.md
    - Liver:
      - General report: Liver/README.md
      - ASCT+B as Graph: Liver/graph.md
      - Report changes: Liver/comments.md
    - Lung:
      - General report: Lung/README.md
      - ASCT+B as Graph: Lung/graph.md
      - Report changes: Lung/comments.md
      - Change suggestions: Lung/change_suggestions.md
    - Lymph Node:
      - General report: Lymph_node/README.md
      - ASCT+B as Graph: Lymph_node/graph.md
      - Report changes: Lymph_node/comments.md
    - Lymph Vasculature:
      - General report: Lymph_vasculature/README.md
      - ASCT+B as Graph: Lymph_vasculature/graph.md
      - Report changes: Lymph_vasculature/comments.md
    - Main Bronchus:
      - General report: Main_Bronchus/README.md
      - ASCT+B as Graph: Main_Bronchus/graph.md
      - Report changes: Main_Bronchus/comments.md
    - Mammary Gland:
      - General report: Mammary_Gland/README.md
      - ASCT+B as Graph: Mammary_Gland/graph.md
      - Report changes: Mammary_Gland/comments.md
    - Muscular System:
      - General report: Muscular_System/README.md
      - ASCT+B as Graph: Muscular_System/graph.md
      - Report changes: Muscular_System/comments.md
    - Ovary:
      - General report: Ovary/README.md
      - ASCT+B as Graph: Ovary/graph.md
      - Report changes: Ovary/comments.md
    - Palatine Tonsil:
      - General report: Palatine_Tonsil/README.md
      - ASCT+B as Graph: Palatine_Tonsil/graph.md
      - Report changes: Palatine_Tonsil/comments.md
    - Pancreas:
      - General report: Pancreas/README.md
      - ASCT+B as Graph: Pancreas/graph.md
      - Report changes: Pancreas/comments.md
      - Change suggestions: Pancreas/change_suggestions.md
    - Peripheral Nervous System:
      - General report: Peripheral_nervous_system/README.md
      - ASCT+B as Graph: Peripheral_nervous_system/graph.md
      - Report changes: Peripheral_nervous_system/comments.md
    - Placenta:
      - General report: Placenta/README.md
      - ASCT+B as Graph: Placenta/graph.md
      - Report changes: Placenta/comments.md
    - Prostate:
      - General report: Prostate/README.md
      - ASCT+B as Graph: Prostate/graph.md
      - Report changes: Prostate/comments.md
    - Skeleton:
      - General report: Skeleton/README.md
      - ASCT+B as Graph: Skeleton/graph.md
      - Report changes: Skeleton/comments.md
    - Skin:
      - General report: Skin/README.md
      - ASCT+B as Graph: Skin/graph.md
      - Report changes: Skin/comments.md
    - Small Intestine:
      - General report: Small_intestine/README.md
      - ASCT+B as Graph: Small_intestine/graph.md
      - Report changes: Small_intestine/comments.md
    - Spinal Cord:
      - General report: Spinal_Cord/README.md
      - ASCT+B as Graph: Spinal_Cord/graph.md
      - Report changes: Spinal_Cord/comments.md
    - Spleen:
      - General report: Spleen/README.md
      - ASCT+B as Graph: Spleen/graph.md
      - Report changes: Spleen/comments.md
    - Thymus:
      - General report: Thymus/README.md
      - ASCT+B as Graph: Thymus/graph.md
      - Report changes: Thymus/comments.md
    - Trachea:
      - General report: Trachea/README.md
      - ASCT+B as Graph: Trachea/graph.md
      - Report changes: Trachea/comments.md
    - Ureter:
      - General report: Ureter/README.md
      - ASCT+B as Graph: Ureter/graph.md
      - Report changes: Ureter/comments.md
    - Urinary Bladder:
      - General report: Urinary_bladder/README.md
      - ASCT+B as Graph: Urinary_bladder/graph.md
      - Report changes: Urinary_bladder/comments.md
    - Uterus:
      - General report: Uterus/README.md
      - ASCT+B as Graph: Uterus/graph.md
      - Report changes: Uterus/comments.md