name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ontology_qc"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: anitacaron/ccf-tools-dep:v1.0.8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: verify and build
        env:
          DEFAULT_BRANCH: master
        run: mkdir -p resources/ASCT-b_tables && cd src && make official_release JOBS=Kidney
