name: Report Release

# Controls when the action will run.
on:
  # Triggers the workflow weekly on Mondays at 6:54 am
  schedule:
    - cron: '54 6 * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job "report-release"
  report-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.23

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: report-release
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: verify and build
        run: mkdir resources/ASCT-b_tables && cd src && make all