name: Release

# Controls when the action will run.
on:
  # Triggers the workflow weekly on Mondays at 6:54 am
  schedule:
   - cron: '54 6 * * 1'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job "report-release"
  report-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: anitacaron/ccf-tools-dep

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: verify and build
        run: mkdir resources/ASCT-b_tables && cd src && make all
      - name: Commit report
        run: |
          git config --global user.name 'Anita Caron'
          git config --global user.email 'anitacaron@users.noreply.github.com'
          git commit -am "Automated report"
          git push
      - name: Release
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false